import { NextResponse } from "next/server";
import { isSignalId } from "@/data/signals";
import { generatePersonalization } from "@/lib/ai";

export const runtime = "nodejs";

interface Body {
  id?: string;
  dominant?: string;
  secondary?: string;
  answers?: Record<number, string>;
  language?: string;
}

/**
 * Invisible personalization endpoint. Runs after payment.
 *
 * Returns a complete PersonalizedResult — generated by the AI when configured,
 * otherwise by the premium deterministic fallback. It NEVER returns an AI error:
 * a clean premium result is always produced. The Signal itself is decided by
 * deterministic scoring, not here.
 */
export async function POST(req: Request) {
  let body: Body;
  try {
    body = (await req.json()) as Body;
  } catch {
    return NextResponse.json({ error: "Invalid request." }, { status: 400 });
  }

  const id = (body.id || "").trim();
  const dominant = body.dominant || "";
  const secondary = body.secondary || "";

  if (!id || !isSignalId(dominant) || !isSignalId(secondary)) {
    return NextResponse.json({ error: "Invalid result." }, { status: 400 });
  }

  const { result, status } = await generatePersonalization({
    id,
    dominant,
    secondary,
    answers: body.answers || {},
    language: body.language,
  });

  // `status` is internal only (pending/completed/fallback/failed) — it is safe
  // to expose for analytics but the UI never surfaces it to the user.
  return NextResponse.json({ result, status });
}
